version: "1.0.0"
requestTimeout: 10000
currentDataSource: "MySQL"
bridges:
    myself:
        app: "sample"
        hostname: "localhost"
        port: 8001

dataSources:
    Couchbase:
        host: "localhost"
        port: "8091"
        bucket: "default"

    MySQL:
        host: "10.40.10.1"
        port: 3306
        user: "root"
        password: "vsadmin"
        database: "kitchen"
