version: "1.0.0"
requestTimeout: 10000
currentDataSource: "MySQL"
dataSources:
    MySQL:
        host: "localhost"
        port: 3306
        user: "root"
        password: "vsadmin"
        database: "kitchen"
